server:
  port: 8763
eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka-servertwo
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/,http://eurekaserverone:8762/eureka/
